create table `rise_item_estados` (
	`id` int (11),
	`item_estado` varchar (300),
	`deleted` tinyint (1),
	`commodity_group_code` text ,
	`order` int (10),
	`display` int (1),
	`note` text 
); 
insert into `rise_item_estados` (`id`, `item_estado`, `deleted`, `commodity_group_code`, `order`, `display`, `note`) values('1','DISPONIBLE','0',NULL,NULL,NULL,NULL);
insert into `rise_item_estados` (`id`, `item_estado`, `deleted`, `commodity_group_code`, `order`, `display`, `note`) values('2','EN MANTENIMIENTO','0',NULL,NULL,NULL,NULL);
insert into `rise_item_estados` (`id`, `item_estado`, `deleted`, `commodity_group_code`, `order`, `display`, `note`) values('3','nuevo','1',NULL,NULL,NULL,NULL);
insert into `rise_item_estados` (`id`, `item_estado`, `deleted`, `commodity_group_code`, `order`, `display`, `note`) values('4','EN CAMPO','0',NULL,NULL,NULL,NULL);
insert into `rise_item_estados` (`id`, `item_estado`, `deleted`, `commodity_group_code`, `order`, `display`, `note`) values('5','NUEVO ESTADO','1',NULL,NULL,NULL,NULL);
insert into `rise_item_estados` (`id`, `item_estado`, `deleted`, `commodity_group_code`, `order`, `display`, `note`) values('6','EN ALMACEN DE PROVEEDOR','0',NULL,NULL,NULL,NULL);
insert into `rise_item_estados` (`id`, `item_estado`, `deleted`, `commodity_group_code`, `order`, `display`, `note`) values('7','TEST','0',NULL,NULL,NULL,NULL);


create table `rise_items` (
	`id` int (11),
	`deleted` tinyint (1),
	`category_id` int (11),
	`estado_id` int (11),
	`codigo` varchar (765),
	`title` text ,
	`description` text ,
	`unit_type` varchar (60),
	`rate` double ,
	`files` text ,
	`show_in_client_portal` tinyint (1),
	`sort` int (11),
	`tax` int (11),
	`tax2` int (11),
	`commodity_code` varchar (300),
	`commodity_barcode` text ,
	`commodity_type` int (11),
	`warehouse_id` int (11),
	`origin` varchar (300),
	`color_id` int (11),
	`style_id` int (11),
	`model_id` int (11),
	`size_id` int (11),
	`unit_id` int (11),
	`sku_code` varchar (600),
	`sku_name` varchar (600),
	`purchase_price` Decimal (17),
	`sub_group` varchar (600),
	`commodity_name` varchar (600),
	`color` text ,
	`guarantee` text ,
	`profif_ratio` text ,
	`parent_id` int (11),
	`attributes` text ,
	`parent_attributes` text ,
	`can_be_sold` varchar (300),
	`can_be_purchased` varchar (300),
	`can_be_manufacturing` varchar (300),
	`can_be_inventory` varchar (300),
	`without_checking_warehouse` int (11),
	`long_descriptions` text ,
	`from_vendor_item` int (11)
); 
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('1','0','2','1','S1114042-01','Baños Portatiles Plástico','Baños Portatiles Plástico','','500','a:1:{i:0;a:4:{s:9:\"file_name\";s:50:\"item_file645bae6d0814e-baño-portatil-plastico.jpg\";s:9:\"file_size\";s:5:\"42456\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('2','1','0','2','S1114042-01\n','01','','01','1111111','a:0:{}','0','0','1','0','01','37909508665',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','00002','','1111111.00','','',NULL,NULL,'',NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0','',NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('3','1','0','1','S1114042-01\n','test','','01','5','a:0:{}','0','0','0','0','test','97403854022',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','00003','','0.00','','',NULL,NULL,'',NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0','',NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('4','0','2','1','S1114042-01','Baño Portatil Fibra','Baño Portatil Fibra','01','200','a:1:{i:0;a:4:{s:9:\"file_name\";s:47:\"item_file645bae4ecc8eb-baño-portatil-fibra.jpg\";s:9:\"file_size\";s:5:\"43666\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0','1','1','xxxxxxxxxxx','11725832383',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','0-00004','','2222.00','','',NULL,NULL,'',NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0','',NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('5','1','0','1','S1114042-01\n','4324234','','01','2','a:0:{}','0','0','0','0','23143','69596179026',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','00005','','2.00','','',NULL,NULL,'',NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0','',NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('6','1','0','1','S1114042-01\n','aaaaaaaaaaaaaaa','','01','0','a:0:{}','0','0','0','0','aaaaaaaaa','47499591038',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','00006','','1111.00','','',NULL,NULL,'',NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0','',NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('7','1','0','0','S1114042-01\n','xxxxxxxxxxxxxxxxxx','','01','4','a:0:{}','0','0','0','0','xxxxxxxxxx','48112029975',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','00007','','4.00','','',NULL,NULL,'',NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0','',NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('8','1','0','1','S1114042-01\n','aaaaaaaaaaaaa','','01','1','a:0:{}','0','0','0','0','aaaaaaaa','66957910572',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','00008','','1.00','','',NULL,NULL,'',NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0','',NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('9','0','2','1','S1114042-01','Baños Portatiles Plástico','Baños Portatiles Plástico','','300','a:1:{i:0;a:4:{s:9:\"file_name\";s:50:\"item_file645bae9060d4d-baño-portatil-plastico.jpg\";s:9:\"file_size\";s:5:\"42456\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('10','0','2','0','S1114042-01','Baños Portatiles Ejecutivo','Baños Portatiles Ejecutivo','','500','a:1:{i:0;a:4:{s:9:\"file_name\";s:52:\"item_file645baea1d30df-baño-portatil-ejecutivo.jpeg\";s:9:\"file_size\";s:6:\"113269\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('11','0','4','1','S1114042-01','Lavaojos','Lavaojos','','200','a:1:{i:0;a:4:{s:9:\"file_name\";s:35:\"item_file645bb13487268-lavaojos.jpg\";s:9:\"file_size\";s:6:\"301785\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('12','0','5','4','S1114042-01','Duchas Portátiles','Duchas Portátiles','','1000','a:1:{i:0;a:4:{s:9:\"file_name\";s:44:\"item_file645bb15e32145-duchas-portatiles.png\";s:9:\"file_size\";s:6:\"412667\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('13','0','6','1','S1114042-01','Bombas de Succión','Bombas de Succión','','800','a:1:{i:0;a:4:{s:9:\"file_name\";s:44:\"item_file645bb1e3dd6be-Bombas-de-succion.png\";s:9:\"file_size\";s:6:\"459462\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('14','0','7','2','S1114042-01','Generadores Eléctricos','Generadores Eléctricos','','800','a:1:{i:0;a:4:{s:9:\"file_name\";s:49:\"item_file645bb2025e9b3-Generadores-electricos.png\";s:9:\"file_size\";s:6:\"181809\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('15','0','3','1','S1114043-02','Lavaderos Portátiles','Lavaderos Portátiles','','500','a:1:{i:0;a:4:{s:9:\"file_name\";s:47:\"item_file645bb516c5594-lavadores-portatiles.jpg\";s:9:\"file_size\";s:5:\"38642\";s:7:\"file_id\";N;s:12:\"service_type\";N;}}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('16','0','0','2','S1114042-01','SERVICIO DE DESINFECCIÓN','Servicio de Fumigación Industrial – Desinsectación en las Instalaciones de la obra del Hospital de Huarmey y campamento.','','1800','','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
insert into `rise_items` (`id`, `deleted`, `category_id`, `estado_id`, `codigo`, `title`, `description`, `unit_type`, `rate`, `files`, `show_in_client_portal`, `sort`, `tax`, `tax2`, `commodity_code`, `commodity_barcode`, `commodity_type`, `warehouse_id`, `origin`, `color_id`, `style_id`, `model_id`, `size_id`, `unit_id`, `sku_code`, `sku_name`, `purchase_price`, `sub_group`, `commodity_name`, `color`, `guarantee`, `profif_ratio`, `parent_id`, `attributes`, `parent_attributes`, `can_be_sold`, `can_be_purchased`, `can_be_manufacturing`, `can_be_inventory`, `without_checking_warehouse`, `long_descriptions`, `from_vendor_item`) values('18','0','2','2','NC.73435','Equipo de medicion de P10','PArticulass','UND','34','a:0:{}','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0.00',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,'can_be_sold','can_be_purchased','can_be_manufacturing','can_be_inventory','0',NULL,NULL);
